<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "miniorange_saml"
 *
 * Auto generated by Extension Builder 2019-05-10
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Miniorange Saml',
    'description' => 'Miniorange Saml (SSO) provides SSO/Login to your TYPO3 site with any SAML compliant Identity Provider (ACTIVE SUPPORT for IdP config). It allows users residing at SAML 2.0 capable Identity Provider to login to your TYPO3 website. We support all known IdPs – Google Apps, ADFS, Azure AD, Okta, Salesforce, Shibboleth, SimpleSAMLphp, OpenAM, Centrify, Ping, RSA, IBM, Oracle, OneLogin, Bitium, WSO2, NetIQ etc.',
    'category' => 'plugin',
    'author' => 'Miniorange',
    'author_email' => 'info@xecurify.com',
    'state' => 'stable',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.2.3',
    'constraints' => [
        'depends' => [
            'typo3' => '8.0.0-9.5.13',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
