<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "miniorange_saml"
 *
 * Auto generated by Extension Builder 2019-05-29
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'SAML SP Single Sign On-(SSO)',
    'description' => 'SAML 2.0 Single Sign On provides SSO/Login to your TYPO3 site with any SAML compliant Identity Provider. (ACTIVE SUPPORT for IdP config)',
    'category' => 'plugin',
    'author' => 'miniOrange',
    'author_email' => 'info@miniorange.com',
    'state' => 'stable',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 1,
    'version' => '1.1.1',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-8.7.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
